server:
  port: 5555

spring:
  application:
    name: travelportalgateway

  cloud:
    gateway:
      routes:
        - id: blogroute
          uri: lb://BLOGSERVICE
          predicates:
            - Path=/travelportal/blog/**
          filters:
            - RewritePath=/travelportal/blog(?<segment>.*), $\{segment}
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
        - id: statsroute
          uri: lb://STATSSERVICE
          predicates:
            - Path=/travelportal/stats/**
          filters:
            - RewritePath=/travelportal/stats(?<segment>.*), $\{segment}
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"



eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    # fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway