
spring:
  application:
    name: travelportalregistry
  profiles:
    active: default   # optional since default

  config:
    import: configserver:http://localhost:8888

encrypt:
  key: topsecret

