GET http://localhost:54424/resources/blogs

###

POST http://localhost:54424/resources/blogs
Content-Type: application/json

{
    "id": 1,
     "blogText": "Das Kindermuseum Schloss Schönbrunn feiert Weihnachten und hat aus diesem Anlass ein buntes Programm für die Kleinen auf die Beine gestellt. Von 13. Dezember bis 9. Jänner warten spannende Highlights wie erlebnisreiche Rätselrallyen, Bastelkurse und wissenswerte Themenführungen, die über traditionelle Weihnachtsbräuche und den kaiserlichen Hof belehren.",
    "author":
    {
      "firstname": "Philipp",
      "lastname" : "Pfeffer"
    },
    "attraction":
    {

      "name": "Schloß Schönbrunn",
      "description": "Altes und bekanntes Schloß in Wien"
    }
}

###

POST http://localhost:59688/resources/blogs
Content-Type: application/json

{
  "id": 1,
  "title": "Neues vom Schloß Schönbrunn",
  "blogText": "Das Kindermuseum Schloss Schönbrunn feiert Weihnachten und hat aus diesem Anlass ein buntes Programm für die Kleinen auf die Beine gestellt. Von 13. Dezember bis 9. Jänner warten spannende Highlights wie erlebnisreiche Rätselrallyen, Bastelkurse und wissenswerte Themenführungen, die über traditionelle Weihnachtsbräuche und den kaiserlichen Hof belehren.",
  "author":
  {
    "id": null,
    "firstname": "Philipp",
    "lastname": "Heitzer"
  },
  "attraction":
  {
    "id": 1,
    "name": "Disco Loco",
    "description": "Billig saufen - 50 Cent pro Vodka Bull"
  }
}

###
GET http://localhost:58159/resources/blogs/1

